# Adapted from https://doc.mergify.io/examples.html#running-ci-pipelines-automatically
# Validate your changes with:
#   $ curl -F 'data=@.mergify.yml' https://gh.mergify.io/validate/

pull_request_rules:
  - name: Automatic merges for Renovate pull requests
    conditions:
      - author~=^renovate\[bot\]$
      - check-success=checks (11)
      - check-success=checks (17)
      - check-success=checks (21)
    actions:
      merge:
        method: squash

  - name: Be author's friend
    conditions:
      - author~=^ubiratansoares
      - check-success=checks (11)
      - check-success=checks (17)
      - check-success=checks (21)
    actions:
      merge:
        method: squash
