# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

inlineHeader = """
Copyright {{props["inceptionYear"]}} {{props["copyrightOwner"]}}
SPDX-License-Identifier: {{props["licenseSPDX"]}}
"""

includes = [
    "**/*.kt",
    "**/*.kts",
    "**/*.yml",
    "**/*.sh",
]

[properties]
inceptionYear = 2025
copyrightOwner = "Dotanuki Labs"
licenseSPDX = "MIT"
