applicationId = "com.duckduckgo.mobile.android"
permissions = [
    "android.permission.ACCESS_COARSE_LOCATION",
    "android.permission.ACCESS_FINE_LOCATION",
    "android.permission.ACCESS_NETWORK_STATE",
    "android.permission.CAMERA",
    "android.permission.FOREGROUND_SERVICE",
    "android.permission.INTERNET",
    "android.permission.MODIFY_AUDIO_SETTINGS",
    "android.permission.POST_NOTIFICATIONS",
    "android.permission.QUERY_ALL_PACKAGES",
    "android.permission.READ_EXTERNAL_STORAGE' maxSdkVersion='29",
    "android.permission.RECEIVE_BOOT_COMPLETED",
    "android.permission.RECORD_AUDIO",
    "android.permission.REQUEST_INSTALL_PACKAGES",
    "android.permission.USE_BIOMETRIC",
    "android.permission.USE_FINGERPRINT",
    "android.permission.WAKE_LOCK",
    "android.permission.WRITE_EXTERNAL_STORAGE' maxSdkVersion='29",
    "com.android.launcher.permission.INSTALL_SHORTCUT",
    "com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE"
]
features = [
    "android.hardware.faketouch",
    "android.hardware.location",
    "android.hardware.microphone",
    "android.hardware.screen.portrait"
]
trustedComponents = [  ]
activities = [
    "com.duckduckgo.app.SelectedTextSearchActivity",
    "com.duckduckgo.app.WidgetThemeConfiguration",
    "com.duckduckgo.app.about.AboutDuckDuckGoActivity",
    "com.duckduckgo.app.accessibility.AccessibilityActivity",
    "com.duckduckgo.app.appearance.AppearanceActivity",
    "com.duckduckgo.app.bookmarks.ui.BookmarksActivity",
    "com.duckduckgo.app.bookmarks.ui.bookmarkfolders.BookmarkFoldersActivity",
    "com.duckduckgo.app.brokensite.BrokenSiteActivity",
    "com.duckduckgo.app.browser.BrowserActivity",
    "com.duckduckgo.app.browser.webview.WebViewActivity",
    "com.duckduckgo.app.downloads.DownloadsActivity",
    "com.duckduckgo.app.email.ui.EmailProtectionUnsupportedActivity",
    "com.duckduckgo.app.feedback.ui.common.FeedbackActivity",
    "com.duckduckgo.app.fire.FireActivity",
    "com.duckduckgo.app.fire.fireproofwebsite.ui.FireproofWebsitesActivity",
    "com.duckduckgo.app.firebutton.FireButtonActivity",
    "com.duckduckgo.app.globalprivacycontrol.ui.GlobalPrivacyControlActivity",
    "com.duckduckgo.app.icon.ui.ChangeIconActivity",
    "com.duckduckgo.app.launch.LaunchBridgeActivity",
    "com.duckduckgo.app.launch.Launcher",
    "com.duckduckgo.app.launch.LauncherBlack",
    "com.duckduckgo.app.launch.LauncherBlue",
    "com.duckduckgo.app.launch.LauncherGold",
    "com.duckduckgo.app.launch.LauncherGreen",
    "com.duckduckgo.app.launch.LauncherPurple",
    "com.duckduckgo.app.launch.LauncherSilhoutte",
    "com.duckduckgo.app.onboarding.ui.OnboardingActivity",
    "com.duckduckgo.app.permissions.PermissionsActivity",
    "com.duckduckgo.app.privacy.ui.AllowListActivity",
    "com.duckduckgo.app.privatesearch.PrivateSearchActivity",
    "com.duckduckgo.app.settings.FireAnimationActivity",
    "com.duckduckgo.app.settings.SettingsActivity",
    "com.duckduckgo.app.sitepermissions.SitePermissionsActivity",
    "com.duckduckgo.app.sitepermissions.permissionsperwebsite.PermissionsPerWebsiteActivity",
    "com.duckduckgo.app.survey.ui.SurveyActivity",
    "com.duckduckgo.app.systemsearch.SystemSearchActivity",
    "com.duckduckgo.app.tabs.ui.TabSwitcherActivity",
    "com.duckduckgo.app.webtrackingprotection.WebTrackingProtectionActivity",
    "com.duckduckgo.app.widget.ui.AddWidgetInstructionsActivity",
    "com.duckduckgo.autoconsent.impl.ui.AutoconsentSettingsActivity",
    "com.duckduckgo.autofill.impl.ui.credential.management.AutofillManagementActivity",
    "com.duckduckgo.macos_impl.MacOsActivity",
    "com.duckduckgo.mobile.android.themepreview.ui.AppComponentsActivity",
    "com.duckduckgo.mobile.android.vpn.apps.ui.ManageRecentAppsProtectionActivity",
    "com.duckduckgo.mobile.android.vpn.apps.ui.TrackingProtectionExclusionListActivity",
    "com.duckduckgo.mobile.android.vpn.breakage.ReportBreakageAppListActivity",
    "com.duckduckgo.mobile.android.vpn.breakage.ReportBreakageCategorySingleChoiceActivity",
    "com.duckduckgo.mobile.android.vpn.service.VpnPermissionRequesterActivity",
    "com.duckduckgo.mobile.android.vpn.ui.onboarding.VpnOnboardingActivity",
    "com.duckduckgo.mobile.android.vpn.ui.report.DeviceShieldAppTrackersInfo",
    "com.duckduckgo.mobile.android.vpn.ui.tracker_activity.AppTPCompanyTrackersActivity",
    "com.duckduckgo.mobile.android.vpn.ui.tracker_activity.DeviceShieldMostRecentActivity",
    "com.duckduckgo.mobile.android.vpn.ui.tracker_activity.DeviceShieldTrackerActivity",
    "com.duckduckgo.networkprotection.impl.about.NetPTermsActivity",
    "com.duckduckgo.networkprotection.impl.about.NetpAboutVpnActivity",
    "com.duckduckgo.networkprotection.impl.about.NetpFaqActivity",
    "com.duckduckgo.networkprotection.impl.exclusion.ui.NetpAppExclusionListActivity",
    "com.duckduckgo.networkprotection.impl.management.NetworkProtectionManagementActivity",
    "com.duckduckgo.networkprotection.impl.settings.NetPNotificationSettingsActivity",
    "com.duckduckgo.networkprotection.impl.settings.NetPVpnSettingsActivity",
    "com.duckduckgo.networkprotection.impl.waitlist.NetPWaitlistActivity",
    "com.duckduckgo.networkprotection.impl.waitlist.NetPWaitlistInvitedActivity",
    "com.duckduckgo.networkprotection.impl.waitlist.NetPWaitlistRedeemCodeActivity",
    "com.duckduckgo.privacy.dashboard.impl.ui.PrivacyDashboardHybridActivity",
    "com.duckduckgo.sync.impl.ui.EnterCodeActivity",
    "com.duckduckgo.sync.impl.ui.ShowCodeActivity",
    "com.duckduckgo.sync.impl.ui.ShowQRCodeActivity",
    "com.duckduckgo.sync.impl.ui.SyncActivity",
    "com.duckduckgo.sync.impl.ui.SyncConnectActivity",
    "com.duckduckgo.sync.impl.ui.SyncInternalSettingsActivity",
    "com.duckduckgo.sync.impl.ui.SyncLoginActivity",
    "com.duckduckgo.sync.impl.ui.setup.SetupAccountActivity",
    "com.duckduckgo.voice.impl.listeningmode.VoiceSearchActivity",
    "com.duckduckgo.windows.impl.ui.WindowsActivity",
    "com.journeyapps.barcodescanner.CaptureActivity"
]
services = [
    "androidx.room.MultiInstanceInvalidationService",
    "androidx.work.impl.background.systemalarm.SystemAlarmService",
    "androidx.work.impl.background.systemjob.SystemJobService",
    "androidx.work.impl.foreground.SystemForegroundService",
    "androidx.work.multiprocess.RemoteWorkManagerService",
    "androidx.work.multiprocess.RemoteWorkerService",
    "com.duckduckgo.app.job.AppConfigurationJobService",
    "com.duckduckgo.app.notification.NotificationHandlerService",
    "com.duckduckgo.mobile.android.vpn.service.DeviceShieldTileService",
    "com.duckduckgo.mobile.android.vpn.service.TrackerBlockingVpnService",
    "com.duckduckgo.mobile.android.vpn.service.state.VpnStateMonitorService",
    "com.duckduckgo.widget.EmptyFavoritesWidgetService",
    "com.duckduckgo.widget.FavoritesWidgetService"
]
receivers = [
    "androidx.work.impl.background.systemalarm.ConstraintProxy$BatteryChargingProxy",
    "androidx.work.impl.background.systemalarm.ConstraintProxy$BatteryNotLowProxy",
    "androidx.work.impl.background.systemalarm.ConstraintProxy$NetworkStateProxy",
    "androidx.work.impl.background.systemalarm.ConstraintProxy$StorageNotLowProxy",
    "androidx.work.impl.background.systemalarm.ConstraintProxyUpdateReceiver",
    "androidx.work.impl.background.systemalarm.RescheduleReceiver",
    "androidx.work.impl.diagnostics.DiagnosticsReceiver",
    "androidx.work.impl.utils.ForceStopRunnable$BroadcastReceiver",
    "com.duckduckgo.app.browser.remotemessage.SharePromoLinkRMFBroadCastReceiver",
    "com.duckduckgo.app.browser.shortcut.ShortcutReceiver",
    "com.duckduckgo.macos_impl.MacOsLinkShareBroadcastReceiver",
    "com.duckduckgo.mobile.android.vpn.appupdates.AppUpdateReceiver",
    "com.duckduckgo.mobile.android.vpn.heartbeat.VpnHeartbeatDeviceBootMonitor",
    "com.duckduckgo.mobile.android.vpn.service.VpnReminderReceiver",
    "com.duckduckgo.networkprotection.impl.notification.NetPEnableReceiver",
    "com.duckduckgo.widget.SearchAndFavoritesWidget",
    "com.duckduckgo.widget.SearchWidget",
    "com.duckduckgo.widget.SearchWidgetLight",
    "com.duckduckgo.widget.VoiceSearchWidgetUpdater",
    "com.duckduckgo.windows.impl.WindowsLinkShareBroadcastReceiver"
]
providers = [
    "androidx.core.content.FileProvider",
    "androidx.startup.InitializationProvider"
]
