applicationId = "org.mozilla.focus"
minSdk = 21
targetSdk = 33
permissions = [
    "com.google.android.gms.permission.AD_ID",
    "org.mozilla.focus.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION",
    "android.permission.DOWNLOAD_WITHOUT_NOTIFICATION",
    "android.permission.FOREGROUND_SERVICE",
    "com.samsung.android.providers.context.permission.WRITE_USE_APP_FEATURE_SURVEY",
    "android.permission.RECEIVE_BOOT_COMPLETED",
    "android.permission.ACCESS_FINE_LOCATION",
    "android.permission.ACCESS_COARSE_LOCATION",
    "android.permission.ACCESS_NETWORK_STATE",
    "android.permission.WAKE_LOCK",
    "android.permission.USE_FINGERPRINT",
    "android.permission.POST_NOTIFICATIONS",
    "android.permission.HIGH_SAMPLING_RATE_SENSORS",
    "com.android.launcher.permission.INSTALL_SHORTCUT",
    "android.permission.READ_MEDIA_VIDEO",
    "android.permission.READ_MEDIA_AUDIO",
    "org.mozilla.focus.permission.RECEIVE_DOWNLOAD_BROADCAST",
    "android.permission.QUERY_ALL_PACKAGES",
    "android.permission.READ_MEDIA_IMAGES",
    "android.permission.RECORD_AUDIO",
    "android.permission.INTERNET",
    "android.permission.USE_BIOMETRIC",
    "com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE",
    "android.permission.WRITE_EXTERNAL_STORAGE' maxSdkVersion='28",
    "android.permission.CAMERA",
    "android.permission.MODIFY_AUDIO_SETTINGS",
    "android.permission.READ_EXTERNAL_STORAGE"
]
features = [  ]
activities = [
    "org.mozilla.focus.activity.IntentReceiverActivity",
    "org.mozilla.focus.activity.MainActivity",
    "org.mozilla.focus.activity.CrashListActivity",
    "org.mozilla.focus.activity.CustomTabActivity",
    "org.mozilla.focus.activity.TextActionActivity",
    "org.mozilla.focus.activity.InstallFirefoxActivity",
    "org.mozilla.focus.activity.EraseShortcutActivity",
    "org.mozilla.focus.activity.EraseAndOpenShortcutActivity",
    "org.mozilla.focus.searchwidget.VoiceSearchActivity",
    "mozilla.components.lib.crash.prompt.CrashReporterActivity",
    "androidx.compose.ui.tooling.PreviewActivity",
    "mozilla.telemetry.glean.debug.GleanDebugActivity",
    "com.google.android.gms.common.api.GoogleApiActivity",
    "com.google.android.play.core.missingsplits.PlayCoreMissingSplitsActivity",
    "com.google.android.play.core.common.PlayCoreDialogWrapperActivity"
]
services = [
    "org.mozilla.focus.customtabs.CustomTabsService",
    "org.mozilla.focus.downloads.DownloadService",
    "org.mozilla.focus.media.MediaSessionService",
    "org.mozilla.focus.session.SessionNotificationService",
    "mozilla.components.lib.crash.handler.CrashHandlerService",
    "mozilla.components.lib.crash.service.SendCrashReportService",
    "mozilla.components.lib.crash.service.SendCrashTelemetryService",
    "org.mozilla.telemetry.schedule.jobscheduler.TelemetryJobService",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab0",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab1",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab2",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab3",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab4",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab5",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab6",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab7",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab8",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab9",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab10",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab11",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab12",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab13",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab14",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab15",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab16",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab17",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab18",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab19",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab20",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab21",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab22",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab23",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab24",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab25",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab26",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab27",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab28",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab29",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab30",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab31",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab32",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab33",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab34",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab35",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab36",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab37",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab38",
    "org.mozilla.gecko.process.GeckoChildProcessServices$tab39",
    "org.mozilla.gecko.media.MediaManager",
    "org.mozilla.gecko.process.GeckoChildProcessServices$gmplugin",
    "org.mozilla.gecko.process.GeckoChildProcessServices$socket",
    "org.mozilla.gecko.process.GeckoChildProcessServices$gpu",
    "org.mozilla.gecko.process.GeckoChildProcessServices$utility",
    "org.mozilla.gecko.process.GeckoChildProcessServices$ipdlunittest",
    "androidx.work.impl.background.systemalarm.SystemAlarmService",
    "androidx.work.impl.background.systemjob.SystemJobService",
    "androidx.work.impl.foreground.SystemForegroundService",
    "androidx.room.MultiInstanceInvalidationService",
    "com.google.android.play.core.assetpacks.AssetPackExtractionService",
    "com.google.android.play.core.assetpacks.ExtractionForegroundService"
]
receivers = [
    "com.adjust.sdk.AdjustReferrerReceiver",
    "org.mozilla.focus.searchwidget.SearchWidgetProvider",
    "androidx.work.impl.utils.ForceStopRunnable$BroadcastReceiver",
    "androidx.work.impl.background.systemalarm.ConstraintProxy$BatteryChargingProxy",
    "androidx.work.impl.background.systemalarm.ConstraintProxy$BatteryNotLowProxy",
    "androidx.work.impl.background.systemalarm.ConstraintProxy$StorageNotLowProxy",
    "androidx.work.impl.background.systemalarm.ConstraintProxy$NetworkStateProxy",
    "androidx.work.impl.background.systemalarm.RescheduleReceiver",
    "androidx.work.impl.background.systemalarm.ConstraintProxyUpdateReceiver",
    "androidx.work.impl.diagnostics.DiagnosticsReceiver",
    "androidx.profileinstaller.ProfileInstallReceiver"
]
providers = [
    "androidx.core.content.FileProvider",
    "androidx.startup.InitializationProvider",
    "mozilla.components.feature.downloads.provider.FileProvider",
    "mozilla.components.feature.prompts.provider.FileProvider",
    "io.sentry.android.core.SentryPerformanceProvider"
]