applicationId = "com.woocommerce.android"
minSdk = 24
targetSdk = 33
permissions = [
    "android.permission.BLUETOOTH_ADMIN' maxSdkVersion='30",
    "android.permission.GET_ACCOUNTS",
    "android.permission.FOREGROUND_SERVICE",
    "android.permission.NFC",
    "android.permission.RECEIVE_BOOT_COMPLETED",
    "android.permission.BLUETOOTH' maxSdkVersion='30",
    "android.permission.ACCESS_FINE_LOCATION",
    "android.permission.ACCESS_COARSE_LOCATION",
    "android.permission.ACCESS_NETWORK_STATE",
    "android.permission.WAKE_LOCK",
    "android.permission.ACCESS_WIFI_STATE",
    "com.woocommerce.android.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION",
    "android.permission.POST_NOTIFICATIONS",
    "com.google.android.c2dm.permission.RECEIVE",
    "android.permission.READ_EXTERNAL_STORAGE' maxSdkVersion='32",
    "android.permission.READ_MEDIA_VIDEO",
    "android.permission.READ_MEDIA_AUDIO",
    "android.permission.ACTION_OPEN_DOCUMENT",
    "android.permission.BLUETOOTH_SCAN",
    "android.permission.READ_MEDIA_IMAGES",
    "android.permission.RUN_USER_INITIATED_JOBS",
    "android.permission.INTERNET",
    "com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE",
    "android.permission.CAMERA",
    "android.permission.WRITE_EXTERNAL_STORAGE' maxSdkVersion='28",
    "android.permission.BLUETOOTH_CONNECT",
    "android.permission.READ_PHONE_STATE"
]
features = [
    "android.hardware.bluetooth",
    "android.hardware.location",
    "android.hardware.wifi",
    "android.hardware.faketouch"
]
activities = [
    "com.woocommerce.android.ui.main.MainActivity",
    "com.woocommerce.android.ui.login.LoginActivity",
    "com.woocommerce.android.ui.login.MagicLinkInterceptActivity",
    "com.woocommerce.android.ui.prefs.AppSettingsActivity",
    "com.woocommerce.android.ui.prefs.UnifiedAboutScreenActivity",
    "com.woocommerce.android.support.WooLogViewerActivity",
    "com.woocommerce.android.support.SSRActivity",
    "com.woocommerce.android.support.requests.SupportRequestFormActivity",
    "com.woocommerce.android.support.help.HelpActivity",
    "zendesk.support.guide.HelpCenterActivity",
    "zendesk.support.guide.ViewArticleActivity",
    "zendesk.support.request.RequestActivity",
    "zendesk.support.requestlist.RequestListActivity",
    "org.wordpress.android.mediapicker.ui.MediaPickerActivity",
    "com.google.mlkit.vision.codescanner.internal.GmsBarcodeScanningDelegateActivity",
    "com.s.p.Dashboard",
    "com.stripe.cots.simulator.SimulatedContactlessPaymentActivity",
    "zendesk.messaging.MessagingActivity",
    "androidx.compose.ui.tooling.PreviewActivity",
    "com.google.android.gms.auth.api.signin.internal.SignInHubActivity",
    "com.google.android.gms.common.api.GoogleApiActivity",
    "com.stripe.stripeterminal.internal.common.usb.UsbEventReceiverActivity",
    "com.google.android.play.core.missingsplits.PlayCoreMissingSplitsActivity",
    "com.google.android.play.core.common.PlayCoreDialogWrapperActivity"
]
services = [
    "com.woocommerce.android.notifications.push.FCMMessageService",
    "com.woocommerce.android.notifications.NotificationsProcessingService",
    "org.wordpress.android.login.LoginWpcomService",
    "com.woocommerce.android.media.ProductImagesService",
    "com.woocommerce.android.media.ProductImagesJobService",
    "com.stripe.cots.aidlservice.CotsService",
    "com.google.android.gms.auth.api.signin.RevocationBoundService",
    "com.google.mlkit.common.internal.MlKitComponentDiscoveryService",
    "com.google.firebase.components.ComponentDiscoveryService",
    "com.google.firebase.messaging.FirebaseMessagingService",
    "com.google.android.gms.measurement.AppMeasurementService",
    "com.google.android.gms.measurement.AppMeasurementJobService",
    "androidx.work.impl.background.systemalarm.SystemAlarmService",
    "androidx.work.impl.background.systemjob.SystemJobService",
    "androidx.work.impl.foreground.SystemForegroundService",
    "androidx.room.MultiInstanceInvalidationService",
    "androidx.camera.core.impl.MetadataHolderService",
    "com.google.android.play.core.assetpacks.AssetPackExtractionService",
    "com.google.android.play.core.assetpacks.ExtractionForegroundService",
    "com.google.android.datatransport.runtime.backends.TransportBackendDiscovery",
    "com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService"
]
receivers = [
    "com.woocommerce.android.ui.appwidgets.stats.today.TodayStatsWidgetProvider",
    "zendesk.support.DeepLinkingBroadcastReceiver",
    "com.google.firebase.iid.FirebaseInstanceIdReceiver",
    "com.google.android.gms.measurement.AppMeasurementReceiver",
    "androidx.work.impl.utils.ForceStopRunnable$BroadcastReceiver",
    "androidx.work.impl.background.systemalarm.ConstraintProxy$BatteryChargingProxy",
    "androidx.work.impl.background.systemalarm.ConstraintProxy$BatteryNotLowProxy",
    "androidx.work.impl.background.systemalarm.ConstraintProxy$StorageNotLowProxy",
    "androidx.work.impl.background.systemalarm.ConstraintProxy$NetworkStateProxy",
    "androidx.work.impl.background.systemalarm.RescheduleReceiver",
    "androidx.work.impl.background.systemalarm.ConstraintProxyUpdateReceiver",
    "androidx.work.impl.diagnostics.DiagnosticsReceiver",
    "com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmManagerSchedulerBroadcastReceiver",
    "androidx.profileinstaller.ProfileInstallReceiver"
]
providers = [
    "androidx.core.content.FileProvider",
    "androidx.startup.InitializationProvider",
    "zendesk.support.SupportSdkStartupProvider",
    "zendesk.support.guide.GuideSdkStartupProvider",
    "com.google.mlkit.common.internal.MlKitInitProvider",
    "com.google.firebase.provider.FirebaseInitProvider",
    "zendesk.belvedere.BelvedereFileProvider",
    "com.squareup.picasso.PicassoProvider",
    "io.sentry.android.core.SentryInitProvider",
    "io.sentry.android.core.SentryPerformanceProvider"
]