name: Publish

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - name: Project Checkout
        uses: actions/checkout@v4.2.0

      - name: Setup JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run Gradle build
        run: ./gradlew assembleExecutable

      - name: Prepare to release
        id: prepare-release
        run: ./scripts/prepare-release.sh

      - name: Create draft release
        uses: softprops/action-gh-release@v2.0.8
        with:
          name: ${{ steps.prepare-release.outputs.version }}
          tag_name: ${{ steps.prepare-release.outputs.version }}
          files: aaw-${{ steps.prepare-release.outputs.version }}.zip
          token: ${{ secrets.DOTANUKI_BOT_TOKEN }}
          generate_release_notes: true
          draft: true
